from __future__ import annotations

from dataclasses import dataclass
import re
import sys
import time
from typing import Any


if __package__ in {None, ""}:
    from pathlib import Path

    project_root = Path(__file__).resolve().parents[3]
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))


try:
    import boto3
except ModuleNotFoundError as exc:  # pragma: no cover - runtime dependency
    boto3 = None
    _BOTO3_IMPORT_ERROR: ModuleNotFoundError | None = exc
else:
    _BOTO3_IMPORT_ERROR = None


IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass(frozen=True)
class AthenaProvisionRequest:
    database_name: str
    raw_bucket: str
    raw_prefix: str
    refined_bucket: str
    refined_prefix: str
    processed_bucket: str
    processed_prefix: str
    target_column: str = "close"
    lookback: int = 60
    repair_tables: bool = True
    replace_tables: bool = False
    workgroup: str = "primary"
    output_s3_uri: str | None = None
    execute: bool = True
    poll_interval_seconds: float = 2.0
    wait_timeout_seconds: float = 300.0


@dataclass(frozen=True)
class AthenaQueryExecutionResult:
    name: str
    sql: str
    executed: bool
    query_execution_id: str | None
    state: str


@dataclass(frozen=True)
class AthenaProvisionResult:
    database_name: str
    raw_table_name: str
    refined_table_name: str
    feature_table_name: str
    future_predict_table_name: str
    executions: tuple[AthenaQueryExecutionResult, ...]


class ProvisionAthenaCatalogUseCase:
    """
    Create an Athena database plus external tables that point to the S3 zones
    generated by the project pipeline.
    """

    def __init__(
        self,
        *,
        region_name: str | None,
        endpoint_url: str | None = None,
    ) -> None:
        self._region_name = region_name
        self._endpoint_url = endpoint_url

    def execute(self, request: AthenaProvisionRequest) -> AthenaProvisionResult:
        self._validate_request(request)

        raw_table_name = "raw_ohlcv"
        refined_table_name = self._build_refined_table_name(
            target_column=request.target_column,
            lookback=request.lookback,
        )
        feature_table_name = self._build_feature_table_name(
            target_column=request.target_column,
            lookback=request.lookback,
        )
        future_predict_table_name = self._build_future_predict_table_name()

        statements: list[tuple[str, str]] = []
        statements.append(
            (
                "create_database",
                self._build_create_database_sql(request.database_name),
            )
        )

        if request.replace_tables:
            statements.extend(
                [
                    (
                        f"drop_{raw_table_name}",
                        self._build_drop_table_sql(request.database_name, raw_table_name),
                    ),
                    (
                        f"drop_{refined_table_name}",
                        self._build_drop_table_sql(request.database_name, refined_table_name),
                    ),
                    (
                        f"drop_{feature_table_name}",
                        self._build_drop_table_sql(request.database_name, feature_table_name),
                    ),
                    (
                        f"drop_{future_predict_table_name}",
                        self._build_drop_table_sql(
                            request.database_name,
                            future_predict_table_name,
                        ),
                    ),
                ]
            )

        statements.extend(
            [
                (
                    f"create_{raw_table_name}",
                    self._build_raw_table_sql(
                        database_name=request.database_name,
                        table_name=raw_table_name,
                        s3_root=self._join_s3_root(request.raw_bucket, request.raw_prefix),
                    ),
                ),
                (
                    f"create_{refined_table_name}",
                    self._build_refined_table_sql(
                        database_name=request.database_name,
                        table_name=refined_table_name,
                        s3_root=self._join_s3_root(
                            request.refined_bucket,
                            request.refined_prefix,
                        ),
                        target_column=request.target_column,
                        lookback=request.lookback,
                    ),
                ),
                (
                    f"create_{feature_table_name}",
                    self._build_feature_table_sql(
                        database_name=request.database_name,
                        table_name=feature_table_name,
                        s3_root=self._join_s3_root(
                            request.processed_bucket,
                            request.processed_prefix,
                        ),
                        target_column=request.target_column,
                        lookback=request.lookback,
                    ),
                ),
                (
                    f"create_{future_predict_table_name}",
                    self._build_future_predict_table_sql(
                        database_name=request.database_name,
                        table_name=future_predict_table_name,
                        s3_root=self._join_s3_root(
                            request.processed_bucket,
                            request.processed_prefix,
                        ),
                    ),
                ),
            ]
        )

        if request.repair_tables:
            statements.extend(
                [
                    (
                        f"repair_{raw_table_name}",
                        self._build_repair_table_sql(request.database_name, raw_table_name),
                    ),
                    (
                        f"repair_{refined_table_name}",
                        self._build_repair_table_sql(request.database_name, refined_table_name),
                    ),
                    (
                        f"repair_{feature_table_name}",
                        self._build_repair_table_sql(request.database_name, feature_table_name),
                    ),
                    (
                        f"repair_{future_predict_table_name}",
                        self._build_repair_table_sql(
                            request.database_name,
                            future_predict_table_name,
                        ),
                    ),
                ]
            )

        if not request.execute:
            return AthenaProvisionResult(
                database_name=request.database_name,
                raw_table_name=raw_table_name,
                refined_table_name=refined_table_name,
                feature_table_name=feature_table_name,
                future_predict_table_name=future_predict_table_name,
                executions=tuple(
                    AthenaQueryExecutionResult(
                        name=name,
                        sql=sql,
                        executed=False,
                        query_execution_id=None,
                        state="SKIPPED",
                    )
                    for name, sql in statements
                ),
            )

        client = self._build_client()
        executions: list[AthenaQueryExecutionResult] = []
        for name, sql in statements:
            query_execution_id = self._start_query(
                client=client,
                sql=sql,
                workgroup=request.workgroup,
                output_s3_uri=request.output_s3_uri,
            )
            state = self._wait_for_query(
                client=client,
                query_execution_id=query_execution_id,
                poll_interval_seconds=request.poll_interval_seconds,
                wait_timeout_seconds=request.wait_timeout_seconds,
            )
            executions.append(
                AthenaQueryExecutionResult(
                    name=name,
                    sql=sql,
                    executed=True,
                    query_execution_id=query_execution_id,
                    state=state,
                )
            )

        return AthenaProvisionResult(
            database_name=request.database_name,
            raw_table_name=raw_table_name,
            refined_table_name=refined_table_name,
            feature_table_name=feature_table_name,
            future_predict_table_name=future_predict_table_name,
            executions=tuple(executions),
        )

    def _build_client(self) -> Any:
        if _BOTO3_IMPORT_ERROR is not None or boto3 is None:
            raise RuntimeError(
                "boto3 is required to provision the Athena catalog. "
                "Install the dependencies from requirements.txt."
            ) from _BOTO3_IMPORT_ERROR
        return boto3.client(
            "athena",
            region_name=self._region_name,
            endpoint_url=self._endpoint_url,
        )

    def _validate_request(self, request: AthenaProvisionRequest) -> None:
        if not IDENTIFIER_PATTERN.match(request.database_name):
            raise ValueError(
                "database_name must match the Athena identifier pattern "
                "[A-Za-z_][A-Za-z0-9_]*."
            )
        if not IDENTIFIER_PATTERN.match(self._build_refined_table_name(
            target_column=request.target_column,
            lookback=request.lookback,
        )):
            raise ValueError("Derived refined table name is not a valid Athena identifier.")
        if not IDENTIFIER_PATTERN.match(self._build_feature_table_name(
            target_column=request.target_column,
            lookback=request.lookback,
        )):
            raise ValueError("Derived feature table name is not a valid Athena identifier.")
        if not IDENTIFIER_PATTERN.match(self._build_future_predict_table_name()):
            raise ValueError("Derived future_predict table name is not a valid Athena identifier.")
        if request.lookback <= 0:
            raise ValueError("lookback must be greater than zero.")
        if not request.raw_bucket.strip():
            raise ValueError("raw_bucket must not be blank.")
        if not request.refined_bucket.strip():
            raise ValueError("refined_bucket must not be blank.")
        if not request.processed_bucket.strip():
            raise ValueError("processed_bucket must not be blank.")
        if request.output_s3_uri is not None and not request.output_s3_uri.startswith("s3://"):
            raise ValueError("output_s3_uri must start with s3:// when provided.")
        if request.poll_interval_seconds <= 0:
            raise ValueError("poll_interval_seconds must be greater than zero.")
        if request.wait_timeout_seconds <= 0:
            raise ValueError("wait_timeout_seconds must be greater than zero.")

    @staticmethod
    def _normalize_identifier(value: str) -> str:
        normalized = re.sub(r"[^A-Za-z0-9_]+", "_", value.strip().lower())
        normalized = re.sub(r"_+", "_", normalized).strip("_")
        if not normalized:
            raise ValueError("Could not derive a valid identifier from the provided value.")
        if normalized[0].isdigit():
            normalized = f"t_{normalized}"
        return normalized

    @classmethod
    def _build_refined_table_name(cls, *, target_column: str, lookback: int) -> str:
        return f"refined_{cls._normalize_identifier(target_column)}_lkb{lookback}"

    @classmethod
    def _build_feature_table_name(cls, *, target_column: str, lookback: int) -> str:
        return f"feature_{cls._normalize_identifier(target_column)}_lkb{lookback}"

    @classmethod
    def _build_future_predict_table_name(cls) -> str:
        return "future_predict"

    @staticmethod
    def _join_s3_root(bucket: str, prefix: str) -> str:
        normalized_prefix = prefix.strip().strip("/")
        if normalized_prefix:
            return f"s3://{bucket}/{normalized_prefix}"
        return f"s3://{bucket}"

    @staticmethod
    def _quote_identifier(identifier: str) -> str:
        return f"`{identifier}`"

    def _qualified_table_name(self, database_name: str, table_name: str) -> str:
        return (
            f"{self._quote_identifier(database_name)}."
            f"{self._quote_identifier(table_name)}"
        )

    def _build_create_database_sql(self, database_name: str) -> str:
        return f"CREATE DATABASE IF NOT EXISTS {self._quote_identifier(database_name)}"

    def _build_drop_table_sql(self, database_name: str, table_name: str) -> str:
        return (
            f"DROP TABLE IF EXISTS {self._qualified_table_name(database_name, table_name)}"
        )

    def _build_repair_table_sql(self, database_name: str, table_name: str) -> str:
        return f"MSCK REPAIR TABLE {self._qualified_table_name(database_name, table_name)}"

    def _build_raw_table_sql(
        self,
        *,
        database_name: str,
        table_name: str,
        s3_root: str,
    ) -> str:
        columns = [
            ("date", "string"),
            ("open", "double"),
            ("high", "double"),
            ("low", "double"),
            ("close", "double"),
            ("adj_close", "double"),
            ("volume", "bigint"),
            ("extracted_at_utc", "string"),
        ]
        partitions = [
            ("source", "string"),
            ("symbol", "string"),
            ("extraction_date", "string"),
        ]
        return self._build_parquet_table_sql(
            database_name=database_name,
            table_name=table_name,
            columns=columns,
            partitions=partitions,
            location=f"{s3_root}/market_data/",
        )

    def _build_refined_table_sql(
        self,
        *,
        database_name: str,
        table_name: str,
        s3_root: str,
        target_column: str,
        lookback: int,
    ) -> str:
        columns: list[tuple[str, str]] = [
            ("target_column", "string"),
            ("split", "string"),
            ("window_start_date", "string"),
            ("window_end_date", "string"),
            ("target_date", "string"),
            ("y_scaled", "double"),
            (f"y_{target_column}", "double"),
        ]
        columns.extend(
            (f"{target_column}_t_minus_{lag}", "double")
            for lag in range(lookback, 0, -1)
        )
        partitions = [
            ("source", "string"),
            ("symbol", "string"),
            ("lookback", "int"),
            ("extraction_date", "string"),
        ]
        return self._build_parquet_table_sql(
            database_name=database_name,
            table_name=table_name,
            columns=columns,
            partitions=partitions,
            location=f"{s3_root}/refined_data/",
        )

    def _build_feature_table_sql(
        self,
        *,
        database_name: str,
        table_name: str,
        s3_root: str,
        target_column: str,
        lookback: int,
    ) -> str:
        columns: list[tuple[str, str]] = [
            ("target_column", "string"),
            ("split", "string"),
            ("window_start_date", "string"),
            ("window_end_date", "string"),
            ("target_date", "timestamp"),
            ("y_scaled", "double"),
            (f"y_{target_column}", "double"),
        ]
        columns.extend(
            (f"{target_column}_t_minus_{lag}", "double")
            for lag in range(lookback, 0, -1)
        )
        columns.extend(
            [
                ("feature_current_price", "double"),
                ("feature_window_mean", "double"),
                ("feature_window_std", "double"),
                ("feature_window_min", "double"),
                ("feature_window_max", "double"),
                ("feature_window_range", "double"),
                ("feature_return_1d", "double"),
                ("feature_return_5d", "double"),
                ("feature_return_10d", "double"),
                ("feature_return_20d", "double"),
                ("feature_sma_gap_5d", "double"),
                ("feature_sma_gap_10d", "double"),
                ("feature_sma_gap_20d", "double"),
                ("feature_ema_gap_5d", "double"),
                ("feature_ema_gap_10d", "double"),
                ("feature_volatility_5d", "double"),
                ("feature_volatility_10d", "double"),
                ("feature_trend_slope_10d", "double"),
                ("feature_trend_slope_20d", "double"),
                ("feature_up_day_ratio_5d", "double"),
                ("feature_up_day_ratio_10d", "double"),
                ("feature_position_in_window", "double"),
                ("feature_window_max_drawdown", "double"),
                ("target_return_1d", "double"),
                ("target_direction", "bigint"),
            ]
        )
        partitions = [
            ("source", "string"),
            ("symbol", "string"),
            ("lookback", "int"),
            ("extraction_date", "string"),
        ]
        return self._build_parquet_table_sql(
            database_name=database_name,
            table_name=table_name,
            columns=columns,
            partitions=partitions,
            location=f"{s3_root}/feature_data/",
        )

    def _build_future_predict_table_sql(
        self,
        *,
        database_name: str,
        table_name: str,
        s3_root: str,
    ) -> str:
        columns = [
            ("target_column", "string"),
            ("generated_at_utc", "string"),
            ("generated_at_token", "string"),
            ("predict_type", "string"),
            ("model_family", "string"),
            ("model_name", "string"),
            ("model_local_path", "string"),
            ("training_manifest_local_path", "string"),
            ("training_generated_at_utc", "string"),
            ("forecast_step", "bigint"),
            ("forecast_date", "string"),
            ("predicted_close", "double"),
            ("predicted_scaled", "double"),
            ("predicted_direction", "bigint"),
            ("predicted_direction_label", "string"),
            ("raw_model_predicted_close", "double"),
            ("prediction_constraint_applied", "boolean"),
            ("prediction_constraint_method", "string"),
            ("prediction_return_cap", "double"),
            ("predicted_step_return", "double"),
            ("horizon_return_from_last_observed", "double"),
            ("price_proxy_return", "double"),
            ("last_observed_date", "string"),
            ("last_observed_close", "double"),
            ("input_window_start_date", "string"),
            ("input_window_end_date", "string"),
            ("input_window_end_close", "double"),
            ("input_window_end_origin", "string"),
            ("observed_points_in_window", "bigint"),
            ("predicted_points_in_window", "bigint"),
            ("recursive_forecast", "boolean"),
            ("is_price_proxy", "boolean"),
            ("price_proxy_method", "string"),
        ]
        partitions = [
            ("source", "string"),
            ("symbol", "string"),
            ("lookback", "int"),
            ("horizon_days", "int"),
            ("extraction_date", "string"),
            ("generated_at", "string"),
        ]
        return self._build_parquet_table_sql(
            database_name=database_name,
            table_name=table_name,
            columns=columns,
            partitions=partitions,
            location=f"{s3_root}/future_predict/",
        )

    def _build_parquet_table_sql(
        self,
        *,
        database_name: str,
        table_name: str,
        columns: list[tuple[str, str]],
        partitions: list[tuple[str, str]],
        location: str,
    ) -> str:
        column_sql = ",\n  ".join(
            f"{self._quote_identifier(name)} {type_name}"
            for name, type_name in columns
        )
        partition_sql = ",\n  ".join(
            f"{self._quote_identifier(name)} {type_name}"
            for name, type_name in partitions
        )
        return (
            f"CREATE EXTERNAL TABLE IF NOT EXISTS "
            f"{self._qualified_table_name(database_name, table_name)} (\n"
            f"  {column_sql}\n"
            f")\n"
            f"PARTITIONED BY (\n"
            f"  {partition_sql}\n"
            f")\n"
            f"STORED AS PARQUET\n"
            f"LOCATION '{location}'"
        )

    def _start_query(
        self,
        *,
        client: Any,
        sql: str,
        workgroup: str,
        output_s3_uri: str | None,
    ) -> str:
        kwargs: dict[str, Any] = {
            "QueryString": sql,
            "WorkGroup": workgroup,
        }
        if output_s3_uri:
            kwargs["ResultConfiguration"] = {"OutputLocation": output_s3_uri}

        try:
            response = client.start_query_execution(**kwargs)
        except Exception as exc:
            message = str(exc)
            if "No output location provided" in message:
                raise RuntimeError(
                    "Athena requires an output S3 location for query results. "
                    "Set ATHENA_OUTPUT_S3_URI in .env or pass "
                    "--athena-output-s3-uri s3://<bucket>/<prefix>/ on the "
                    "script command. If you only need local/S3 forecast files "
                    "and do not want Athena catalog repair, pass --skip-athena."
                ) from exc
            raise
        return str(response["QueryExecutionId"])

    def _wait_for_query(
        self,
        *,
        client: Any,
        query_execution_id: str,
        poll_interval_seconds: float,
        wait_timeout_seconds: float,
    ) -> str:
        deadline = time.monotonic() + wait_timeout_seconds
        while True:
            response = client.get_query_execution(QueryExecutionId=query_execution_id)
            state = str(response["QueryExecution"]["Status"]["State"])
            if state in {"SUCCEEDED", "FAILED", "CANCELLED"}:
                if state != "SUCCEEDED":
                    reason = response["QueryExecution"]["Status"].get(
                        "StateChangeReason",
                        "Unknown Athena error.",
                    )
                    raise RuntimeError(
                        f"Athena query {query_execution_id} finished with state {state}: {reason}"
                    )
                return state

            if time.monotonic() >= deadline:
                raise TimeoutError(
                    "Timed out while waiting for Athena query "
                    f"{query_execution_id} to finish."
                )
            time.sleep(poll_interval_seconds)


def main() -> int:
    print(
        "ProvisionAthenaCatalogUseCase is a library module. "
        "Use `python scripts/provision_athena.py --help` to provision the Athena catalog."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
